[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
authors = ["Silitics GmbH <info@silitics.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/silitics/si-rust-libs/"

[workspace.dependencies]
console = "0.15.11"
tracing = "0.1.41"
